version: '2'
services:

  java-8-base:
    image: 'teradatalabs/centos6-java8-oracle:${DOCKER_IMAGES_VERSION}'
    volumes:
      - ../..:/docker/volumes/conf

  application-runner:
    extends:
      service: java-8-base
    hostname: application-runner
    volumes:
      - ${PRESTO_CLI_JAR}:/docker/volumes/presto-cli/presto-cli-executable.jar
      - ${PRODUCT_TESTS_JAR}:/docker/volumes/presto-product-tests/presto-product-tests-executable.jar
      - ../../../conf/tempto/tempto-configuration-for-docker-default.yaml:/docker/volumes/tempto/tempto-configuration-local.yaml
      - ../../../target/test-reports:/docker/volumes/test-reports
