hdfs:
  username: mapr
  webhdfs:
    host: ${databases.hive.host}
    port: 14000

databases:
  hive:
    host: hadoop-master
    jdbc_user: mapr
    jdbc_password: mapr
  presto:
    host: presto-master
    configured_hdfs_user: hive
  cassandra:
    host: cassandra
    port: 9042
    default_schema: test
    skip_create_schema: false
    table_manager_type: cassandra
