databases:
  presto:
    port: 8080
    jdbc_driver_class: com.teradata.presto.jdbc42.Driver
    jdbc_url:  jdbc:presto://${databases.presto.host}:${databases.presto.port}/hive/${databases.hive.schema};TimeZoneID=Africa/Abidjan;
