version: '2'
services:

  ldapserver:
    image: 'teradatalabs/centos6-java8-oracle-openldap:${DOCKER_IMAGES_VERSION}'

  presto-master:
    image: 'teradatalabs/centos6-java8-oracle-ldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-master run
    ports:
      - '7778:7778'
    networks:
      default:
        aliases:
         - presto-master.docker.cluster
    depends_on:
      - ldapserver

  presto-worker-1:
    image: 'teradatalabs/centos6-java8-oracle-ldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-worker-1 run
    networks:
      default:
        aliases:
         - presto-worker-1.docker.cluster
    depends_on:
      - presto-master
    volumes_from:
      - presto-master

  presto-worker-2:
    image: 'teradatalabs/centos6-java8-oracle-ldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-worker-2 run
    networks:
      default:
        aliases:
         - presto-worker-2.docker.cluster
    depends_on:
      - presto-master
    volumes_from:
      - presto-master

  application-runner:
    image: 'teradatalabs/centos6-java8-oracle-ldap:${DOCKER_IMAGES_VERSION}'
